# Generated by Django 5.0.4 on 2024-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='departure_time',
            field=models.TimeField(default='08:30'),
        ),
    ]
