# Generated by Django 5.0.4 on 2024-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_trajet_first_name_trajet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='profile_picture',
            field=models.ImageField(default='None', upload_to='images/'),
            preserve_default=False,
        ),
    ]
